services:
  redis:
    image: redis:alpine
    container_name: siped_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: siped_web
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - shared_data:/app/datos_usuarios
    depends_on:
      - redis

  worker:
    build: .
    container_name: siped_worker
    restart: always
    command: celery -A tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - shared_data:/app/datos_usuarios
    depends_on:
      - redis

volumes:
  shared_data:
