DEPENDENCIAS_POR_LOCALIDAD = {
    "1": {
        "92": "JUZGADO DE PAZ",
    },
    "2": {
        "95": "JUZGADO DE PAZ",
    },
    "3": {
        "77": "EXCMA. CAMARA DE APELACIONES EN LO CIVIL, COMERCIAL, LABORAL Y DE MINERIA DE LA SEGUNDA CIRCUNSCRIPCION JUDICIAL",
        "76": "JUZGADO DE PAZ",
        "102": "JUZGADO DE PRIMERA INSTANCIA DE LA FAMILIA",
        "79": "JUZGADO DE PRIMERA INSTANCIA NRO. DOS EN LO CIVIL, COMERCIAL, LABORAL Y DE MINERIA",
        "80": "JUZGADO DE PRIMERA INSTANCIA NRO. UNO EN LO CIVIL, COMERCIAL, LABORAL Y DE MINERIA",
    },
    "4": {
        "89": "JUZGADO DE PAZ",
        "116": "JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL, COMERCIAL, LABORAL, DE MINERIA Y DE FAMILIA",
    },
    "5": {
        "544": "DEFENSORIA PUBLICA OFICIAL DE PRIMERA INSTANCIA Nº DOS",
        "87": "JUZGADO DE PAZ",
        "63": "JUZGADO PROVINCIAL DE PRIMERA INSTANCIA NRO. UNO EN LO CIVIL, COMERCIAL, LABORAL, DE MINERIA Y DE FAMILIA",
    },
    "6": {
        "97": "JUZGADO DE PAZ",
    },
    "7": {
        "60": "JUZGADO DE PAZ",
    },
    "8": {
        "96": "JUZGADO DE PAZ",
    },
    "9": {
        "93": "JUZGADO DE PAZ",
    },
    "10": {
        "59": "JUZGADO DE PAZ",
    },
    "11": {
        "88": "JUZGADO DE PAZ",
        "119": "JUZGADO DE PRIMERA INSTANCIA EN LO CIVIL, COMERCIAL, LABORAL, MINERIA Y DE FAMILIA(LAS HERAS)",
    },
    "12": {
        "94": "JUZGADO DE PAZ",
    },
    "13": {
        "90": "JUZGADO DE PAZ",
    },
    "14": {
        "54": "JUZGADO DE PAZ",
        "51": "JUZGADO DE PRIMERA INSTANCIA N° UNO EN LO CIVIL, COMERCIAL, LABORAL Y DE MINERIA",
    },
    "15": {
        "49": "JUZGADO DE PAZ",
        "47": "JUZGADO DE PRIMERA INSTANCIA NRO. UNO EN LO CIVIL, COMERCIAL, LABORAL, DE MINERIA Y DE FAMILIA",
    },
    "16": {
        "44": "JUZGADO DE PAZ",
        "43": "JUZGADO DE PRIMERA INSTANCIA NRO. 1 EN LO CIVIL, COMERCIAL, LABORAL, DE MINERIA Y DE FAMILIA",
    },
    "17": {
        "38": "JUZGADO DE PAZ",
    },
    "18": {
        "9": "EXCMA. CAMARA DE APELACIONES EN LO CIVIL, COMERCIAL, LABORAL Y DE MINERIA DE LA PRIMERA CIRCUNSCRIPCION JUDICIAL",
        "30": "JUZGADO DE PAZ",
        "134": "JUZGADO DE PRIMERA INSTANCIA DE FAMILIA Nº 3",
        "18": "JUZGADO DE PRIMERA INSTANCIA DE LA FAMILIA",
        "19": "JUZGADO DE PRIMERA INSTANCIA DE LA FAMILIA NRO. 2",
        "14": "JUZGADO DE PRIMERA INSTANCIA Nro. DOS EN LO CIVIL, COMERCIAL, LABORAL Y DE MINERIA",
        "13": "JUZGADO DE PRIMERA INSTANCIA NRO. UNO EN LO CIVIL, COMERCIAL, LABORAL Y DE MINERIA",
        "109": "LABORATORIO REGIONAL DE INVESTIGACION FORENSE - ZONA SUR",
        "34": "SECRETARIA CIVIL EXCMO. TRIBUNAL SUPERIOR DE JUSTICIA",
    },
    "19": {
        "3": "JUZGADO DE PAZ",
        "5": "JUZGADO PROVINCIAL DE PRIMERA INSTANCIA NRO. UNO EN LO CIVIL, COMERCIAL, LABORAL, DE MINERIA Y DE FAMILIA",
    },
    "20": {
        "1": "JUZGADO DE PAZ",
    },
    "22": {
        "107": "JUZGADO DE PAZ",
    },
    "24": {
        "118": "JUZGADO DE PAZ",
    },
    "3526": {
    },
}
